[
  {
    menuId: 15,
    parentId: 2,
    parentName: null,
    name: "查看",
    url: null,
    perms: "sys:user:page,sys:user:info",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 540,
    parentId: 342,
    parentName: null,
    name: "配置",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 545,
    parentId: 70,
    parentName: null,
    name: "充值订单",
    url: "",
    perms: "suer:user:update",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 546,
    parentId: 70,
    parentName: null,
    name: "提现订单",
    url: "",
    perms: "suer:user:tixian",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 547,
    parentId: 70,
    parentName: null,
    name: "用户基础认证",
    url: "",
    perms: "suer:user:jichu",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 548,
    parentId: 70,
    parentName: null,
    name: "用户高级认证",
    url: "",
    perms: "suer:user:gaoji",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 549,
    parentId: 70,
    parentName: null,
    name: "待处理提醒",
    url: "",
    perms: "suer:user:tixingall",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 301,
    parentId: 300,
    parentName: null,
    name: "添加公告",
    url: "",
    perms: "shop:notice:save",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 302,
    parentId: 300,
    parentName: null,
    name: "修改公告",
    url: "",
    perms: "shop:notice:update",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 303,
    parentId: 300,
    parentName: null,
    name: "查看公告",
    url: "",
    perms: "shop:notice:info,shop:notice:page",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 305,
    parentId: 300,
    parentName: null,
    name: "删除公告",
    url: "",
    perms: "shop:notice:delete",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 313,
    parentId: 312,
    parentName: null,
    name: "新增地址",
    url: "",
    perms: "admin:area:save",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 314,
    parentId: 312,
    parentName: null,
    name: "修改地址",
    url: "",
    perms: "admin:area:update",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 315,
    parentId: 312,
    parentName: null,
    name: "删除地址",
    url: "",
    perms: "admin:area:delete",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 571,
    parentId: 565,
    parentName: null,
    name: "谷歌验证",
    url: "",
    perms: "sys:user:upgogle",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 316,
    parentId: 312,
    parentName: null,
    name: "查看地址",
    url: "",
    perms: "admin:area:info,admin:area:page,admin:area:list",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 338,
    parentId: 337,
    parentName: null,
    name: "总充提报表",
    url: "report/all-filling",
    perms: "",
    type: 1,
    icon: "order",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 339,
    parentId: 337,
    parentName: null,
    name: "代理商充提报表",
    url: "report/agent-filling",
    perms: "",
    type: 1,
    icon: "order",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 340,
    parentId: 337,
    parentName: null,
    name: "用户收益报表",
    url: "report/income",
    perms: "",
    type: 1,
    icon: "order",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 374,
    parentId: 365,
    parentName: null,
    name: "理财配置",
    url: "mining/finance",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 375,
    parentId: 365,
    parentName: null,
    name: "矿机配置",
    url: "mining/mining",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 376,
    parentId: 365,
    parentName: null,
    name: "理财订单",
    url: "mining/finance-order",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 377,
    parentId: 365,
    parentName: null,
    name: "矿机订单",
    url: "mining/mining-order",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 378,
    parentId: 365,
    parentName: null,
    name: "质押借币订单",
    url: "mining/pledge-order",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 132,
    parentId: 131,
    parentName: null,
    name: "查看",
    url: "",
    perms: "shop:pickAddr:page",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 133,
    parentId: 131,
    parentName: null,
    name: "保存",
    url: "",
    perms: "shop:pickAddr:save",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 134,
    parentId: 131,
    parentName: null,
    name: "修改",
    url: "",
    perms: "shop:pickAddr:update,shop:pickAddr:info",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 135,
    parentId: 131,
    parentName: null,
    name: "删除",
    url: "",
    perms: "shop:pickAddr:delete",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 137,
    parentId: 136,
    parentName: null,
    name: "查看",
    url: "",
    perms: "prod:category:page",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 138,
    parentId: 136,
    parentName: null,
    name: "新增",
    url: "",
    perms: "prod:category:save",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 139,
    parentId: 136,
    parentName: null,
    name: "修改",
    url: "",
    perms: "prod:category:info,prod:category:update",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 140,
    parentId: 136,
    parentName: null,
    name: "删除",
    url: "",
    perms: "prod:category:delete",
    type: 2,
    icon: null,
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 397,
    parentId: 396,
    parentName: null,
    name: "机器人刷单管理",
    url: "robot/robot-buy",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 398,
    parentId: 396,
    parentName: null,
    name: "机器人订单管理",
    url: "robot/robot-order",
    perms: "",
    type: 1,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 400,
    parentId: 399,
    parentName: null,
    name: "代理商",
    url: "user-relation/agent",
    perms: "",
    type: 1,
    icon: "vip",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 416,
    parentId: 0,
    parentName: null,
    name: "隐藏菜单",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 164,
    parentId: 163,
    parentName: null,
    name: "查看",
    url: "",
    perms:
      "shop:transport:page,shop:shopDetail:info,shop:transfee:info,admin:area:page,shop:transcity:info",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 165,
    parentId: 163,
    parentName: null,
    name: "修改",
    url: "",
    perms:
      "shop:transport:update,shop:transport:info,shop:transfee:update,admin:area:page",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 421,
    parentId: 405,
    parentName: null,
    name: "买入委托(ETF)",
    url: "etf-spots/buy-order",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 166,
    parentId: 163,
    parentName: null,
    name: "新增",
    url: "",
    perms: "shop:transport:save,shop:transfee:save",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 422,
    parentId: 405,
    parentName: null,
    name: "卖出委托(ETF)",
    url: "etf-spots/sell-order",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 167,
    parentId: 163,
    parentName: null,
    name: "删除",
    url: "",
    perms: "shop:transport:delete,shop:transfee:delete",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 423,
    parentId: 405,
    parentName: null,
    name: "成交记录(ETF)",
    url: "etf-spots/transaction-record",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 424,
    parentId: 405,
    parentName: null,
    name: "交易对(ETF)",
    url: "etf-spots/transaction-pairs",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 425,
    parentId: 409,
    parentName: null,
    name: "买入委托(DC)",
    url: "cryptos-spots/buy-order",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 426,
    parentId: 409,
    parentName: null,
    name: "卖出委托(DC)",
    url: "cryptos-spots/sell-order",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 427,
    parentId: 409,
    parentName: null,
    name: "成交记录(DC)",
    url: "cryptos-spots/transaction-record",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 428,
    parentId: 409,
    parentName: null,
    name: "交易对(DC)",
    url: "cryptos-spots/transaction-pairs",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 430,
    parentId: 413,
    parentName: null,
    name: "买入委托(US)",
    url: "us-spots/buy-order",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 175,
    parentId: 174,
    parentName: null,
    name: "查看",
    url: "",
    perms: "admin:indexImg:page",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 431,
    parentId: 413,
    parentName: null,
    name: "卖入委托(US)",
    url: "us-spots/sell-order",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 176,
    parentId: 174,
    parentName: null,
    name: "新增",
    url: "",
    perms: "admin:indexImg:save",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 432,
    parentId: 413,
    parentName: null,
    name: "成交记录(US)",
    url: "us-spots/transaction-record",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 177,
    parentId: 174,
    parentName: null,
    name: "修改",
    url: "",
    perms: "admin:indexImg:info,admin:indexImg:update",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 433,
    parentId: 413,
    parentName: null,
    name: "交易对(US)",
    url: "us-spots/transaction-pairs",
    perms: "",
    type: 1,
    icon: "store",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 178,
    parentId: 174,
    parentName: null,
    name: "删除",
    url: "",
    perms: "admin:indexImg:delete",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 472,
    parentId: 401,
    parentName: null,
    name: "修改",
    url: "",
    perms: "sys:role:update",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 495,
    parentId: 350,
    parentName: null,
    name: "删除",
    url: "",
    perms: "sys:role:delete",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 240,
    parentId: 239,
    parentName: null,
    name: "添加商品分组",
    url: "",
    perms: "prod:prodTag:save",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 241,
    parentId: 239,
    parentName: null,
    name: "修改商品分组",
    url: "",
    perms: "prod:prodTag:update",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 242,
    parentId: 239,
    parentName: null,
    name: "删除商品分组",
    url: "",
    perms: "prod:prodTag:delete",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 243,
    parentId: 239,
    parentName: null,
    name: "查看商品分组",
    url: "",
    perms: "prod:prodTag:info,prod:prodTag:page",
    type: 2,
    icon: "",
    orderNum: 0,
    list: null,
    appType: "1",
  },
  {
    menuId: 2,
    parentId: 1,
    parentName: null,
    name: "提现订单",
    url: "order/withdraw",
    perms: "",
    type: 1,
    icon: "admin",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 16,
    parentId: 2,
    parentName: null,
    name: "新增",
    url: "",
    perms: "sys:user:save,sys:role:list",
    type: 2,
    icon: "",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 300,
    parentId: 63,
    parentName: null,
    name: "永续持仓单(外汇)",
    url: "shop/transport",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 561,
    parentId: 352,
    parentName: null,
    name: "系统",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 70,
    parentId: 34,
    parentName: null,
    name: "综合查询",
    url: "user/user",
    perms: "",
    type: 1,
    icon: "sousuo",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 343,
    parentId: 342,
    parentName: null,
    name: "汇率配置",
    url: "config/exchange-rate-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 372,
    parentId: 367,
    parentName: null,
    name: "C2C支付方式模板",
    url: "order/cTwoc",
    perms: "",
    type: 1,
    icon: "geren",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 401,
    parentId: 399,
    parentName: null,
    name: "推荐关系",
    url: "user-relation/recommend",
    perms: "",
    type: 1,
    icon: "prod",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 434,
    parentId: 385,
    parentName: null,
    name: "ETF总类管理",
    url: "subscribe/subscribe-general",
    perms: "",
    type: 1,
    icon: "shezhi",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 437,
    parentId: 436,
    parentName: null,
    name: "币币交易单",
    url: "order/order",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 440,
    parentId: 429,
    parentName: null,
    name: "行情管理(ETF)",
    url: "etf-spots/etf-markets-config",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 444,
    parentId: 406,
    parentName: null,
    name: "永续合约(ETF)",
    url: "etf-spots/etf-transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 447,
    parentId: 410,
    parentName: null,
    name: "永续持仓单(DC)",
    url: "cryptos-spots/cryptos-spots-transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 451,
    parentId: 414,
    parentName: null,
    name: "永续持仓单(US)",
    url: "us-spots/us-transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 455,
    parentId: 411,
    parentName: null,
    name: "行情管理(DC)",
    url: "cryptos-spots/cryptos-markets-config",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 458,
    parentId: 415,
    parentName: null,
    name: "行情管理(US)",
    url: "us-spots/us-markets-config",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 461,
    parentId: 412,
    parentName: null,
    name: "行情管理(外汇)",
    url: "shop/shop-markets-config",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 473,
    parentId: 0,
    parentName: null,
    name: "美股",
    url: "",
    perms: "",
    type: 0,
    icon: "tubiao",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 474,
    parentId: 473,
    parentName: null,
    name: "现货",
    url: "",
    perms: "",
    type: 0,
    icon: "down",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 499,
    parentId: 496,
    parentName: null,
    name: "现货",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 500,
    parentId: 497,
    parentName: null,
    name: "现货",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 501,
    parentId: 498,
    parentName: null,
    name: "合约",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 1,
    list: null,
    appType: "1",
  },
  {
    menuId: 515,
    parentId: 497,
    parentName: null,
    name: "卖出委托(ETF)",
    url: "etf-spots/sell-order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 528,
    parentId: 498,
    parentName: null,
    name: "永续持仓单(外汇)",
    url: "shop/transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 17,
    parentId: 2,
    parentName: null,
    name: "修改",
    url: "",
    perms: "sys:user:update,sys:role:list",
    type: 2,
    icon: "",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 562,
    parentId: 352,
    parentName: null,
    name: "系统参数",
    url: "sys-config/root2-sys-config",
    perms: "",
    type: 1,
    icon: "form",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 312,
    parentId: 1,
    parentName: null,
    name: "充值订单",
    url: "order/rechange",
    perms: "",
    type: 1,
    icon: "dangdifill",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 380,
    parentId: 367,
    parentName: null,
    name: "C2C支付方式管理",
    url: "c2c/c2c_pay_mgr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 131,
    parentId: 63,
    parentName: null,
    name: "永续委托单(外汇)",
    url: "shop/hotSearch",
    perms: "",
    type: 1,
    icon: "form",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 136,
    parentId: 34,
    parentName: null,
    name: "用户基础管理",
    url: "user/mange",
    perms: "",
    type: 1,
    icon: "admin",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 402,
    parentId: 399,
    parentName: null,
    name: "用户基础认证",
    url: "user-relation/basics",
    perms: "",
    type: 1,
    icon: "shoucang",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 417,
    parentId: 342,
    parentName: null,
    name: "停盘配置",
    url: "config/suspension",
    perms: "",
    type: 1,
    icon: "system",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 435,
    parentId: 385,
    parentName: null,
    name: "ETF品种管理",
    url: "subscribe/subscribe-variety",
    perms: "",
    type: 1,
    icon: "shezhi",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 439,
    parentId: 429,
    parentName: null,
    name: "ETF币对管理",
    url: "etf-spots/etf-market-variety",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 445,
    parentId: 406,
    parentName: null,
    name: "永续委托单(ETF)",
    url: "etf-spots/etf-hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 448,
    parentId: 410,
    parentName: null,
    name: "永续委托单(DC)",
    url: "cryptos-spots/cryptos-hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 452,
    parentId: 414,
    parentName: null,
    name: "永续委托单(US)",
    url: "us-spots/us-hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 466,
    parentId: 411,
    parentName: null,
    name: "行情品种管理(DC)",
    url: "cryptos-spots/cryptos-variety",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 470,
    parentId: 412,
    parentName: null,
    name: "行情品种管理(外汇)",
    url: "shop/shop-variety",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 471,
    parentId: 415,
    parentName: null,
    name: "行情品种管理(US)",
    url: "us-spots/us-variety",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 475,
    parentId: 473,
    parentName: null,
    name: "卖出委托(美股)",
    url: "us-spots/sell-order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 496,
    parentId: 0,
    parentName: null,
    name: "数字货币",
    url: "",
    perms: "",
    type: 0,
    icon: "tubiao",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 502,
    parentId: 496,
    parentName: null,
    name: "卖出委托(DC)",
    url: "cryptos-spots/sell-order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 2,
    list: null,
    appType: "1",
  },
  {
    menuId: 516,
    parentId: 497,
    parentName: null,
    name: "买入委托(ETF)",
    url: "etf-spots/buy-order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 529,
    parentId: 498,
    parentName: null,
    name: "永续委托单(外汇)",
    url: "shop/hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 18,
    parentId: 2,
    parentName: null,
    name: "删除",
    url: "",
    perms: "sys:user:delete",
    type: 2,
    icon: "",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 541,
    parentId: 342,
    parentName: null,
    name: "内容",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 563,
    parentId: 352,
    parentName: null,
    name: "系统参数（ROOT）",
    url: "sys-config/root-sys-config",
    perms: "",
    type: 1,
    icon: "form",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 381,
    parentId: 367,
    parentName: null,
    name: "C2C承兑商管理",
    url: "c2c/c2c-pay-trader",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 388,
    parentId: 385,
    parentName: null,
    name: "申购管理",
    url: "subscribe/subscribe-mgr",
    perms: "",
    type: 1,
    icon: "shezhi",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 403,
    parentId: 399,
    parentName: null,
    name: "用户高级认证",
    url: "user-relation/senior",
    perms: "",
    type: 1,
    icon: "shoucangfill",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 163,
    parentId: 63,
    parentName: null,
    name: "交割合约单(外汇)",
    url: "shop/pickAddr",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 441,
    parentId: 429,
    parentName: null,
    name: "永续合约管理(ETF)",
    url: "etf-spots/etf-sustainable",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 443,
    parentId: 406,
    parentName: null,
    name: "交割合约单(ETF)",
    url: "etf-spots/etf-pickAddr",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 449,
    parentId: 410,
    parentName: null,
    name: "交割合约单(DC)",
    url: "cryptos-spots/cryptos-pickAddr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 453,
    parentId: 414,
    parentName: null,
    name: "交割合约单(US)",
    url: "us-spots/us-pickAddr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 456,
    parentId: 411,
    parentName: null,
    name: "永续合约管理(DC)",
    url: "cryptos-spots/cryptos-sustainable",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 459,
    parentId: 415,
    parentName: null,
    name: "永续合约管理(US)",
    url: "us-spots/us-sustainable",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 462,
    parentId: 412,
    parentName: null,
    name: "永续合约管理(外汇)",
    url: "shop/shop-sustainable",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 476,
    parentId: 473,
    parentName: null,
    name: "买入委托(美股)",
    url: "us-spots/buy-order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 493,
    parentId: 1,
    parentName: null,
    name: "银行卡支付方式模板",
    url: "order/bank",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 239,
    parentId: 34,
    parentName: null,
    name: "用户管理",
    url: "user/manger",
    perms: "prod:prodTag",
    type: 1,
    icon: "geren",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 497,
    parentId: 0,
    parentName: null,
    name: "ETF",
    url: "",
    perms: "",
    type: 0,
    icon: "tubiao",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 503,
    parentId: 496,
    parentName: null,
    name: "买入委托(DC)",
    url: "cryptos-spots/buy-order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 3,
    list: null,
    appType: "1",
  },
  {
    menuId: 517,
    parentId: 497,
    parentName: null,
    name: "交易对(ETF)",
    url: "etf-spots/transaction-pairs",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 530,
    parentId: 498,
    parentName: null,
    name: "交割合约单(外汇)",
    url: "shop/pickAddr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 538,
    parentId: 352,
    parentName: null,
    name: "管理",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 348,
    parentId: 342,
    parentName: null,
    name: "用户端内容管理",
    url: "config/user",
    perms: "",
    type: 1,
    icon: "admin",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 382,
    parentId: 367,
    parentName: null,
    name: "C2C广告配置",
    url: "c2c/c2c-pay-ad",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 389,
    parentId: 385,
    parentName: null,
    name: "用户申购记录",
    url: "subscribe/subscribe-recorder",
    perms: "",
    type: 1,
    icon: "shezhi",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 404,
    parentId: 399,
    parentName: null,
    name: "人工重置管理",
    url: "user-relation/reset",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 418,
    parentId: 34,
    parentName: null,
    name: "行情管理",
    url: "config/markets-config",
    perms: "",
    type: 1,
    icon: "form",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 174,
    parentId: 63,
    parentName: null,
    name: "交割场控设置(外汇)",
    url: "admin/indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 442,
    parentId: 429,
    parentName: null,
    name: "交割合约管理(ETF)",
    url: "etf-spots/etf-delivery",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 446,
    parentId: 406,
    parentName: null,
    name: "交割场控设置(ETF)",
    url: "etf-spots/etf-indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 450,
    parentId: 410,
    parentName: null,
    name: "交割场控设置(DC)",
    url: "cryptos-spots/cryptos-indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 454,
    parentId: 414,
    parentName: null,
    name: "交割场控设置(US)",
    url: "us-spots/us-indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 457,
    parentId: 411,
    parentName: null,
    name: "交割合约管理(DC)",
    url: "cryptos-spots/cryptos-delivery",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 460,
    parentId: 415,
    parentName: null,
    name: "交割合约管理(US)",
    url: "us-spots/us-delivery",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 463,
    parentId: 412,
    parentName: null,
    name: "交割合约管理(外汇)",
    url: "shop/shop-delivery",
    perms: "",
    type: 1,
    icon: "bianji",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 480,
    parentId: 473,
    parentName: null,
    name: "交易对(美股)",
    url: "us-spots/transaction-pairs",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 494,
    parentId: 1,
    parentName: null,
    name: "银行卡支付方式管理",
    url: "c2c/bank_pay_mgr",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 498,
    parentId: 0,
    parentName: null,
    name: "外汇",
    url: "",
    perms: "",
    type: 0,
    icon: "tubiao",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 504,
    parentId: 496,
    parentName: null,
    name: "交易对(DC)",
    url: "cryptos-spots/transaction-pairs",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 4,
    list: null,
    appType: "1",
  },
  {
    menuId: 518,
    parentId: 497,
    parentName: null,
    name: "合约",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 531,
    parentId: 498,
    parentName: null,
    name: "交割场控设置(外汇)",
    url: "admin/indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 331,
    parentId: 352,
    parentName: null,
    name: "菜单管理",
    url: "sys/menu",
    perms: "",
    type: 1,
    icon: "form",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 349,
    parentId: 342,
    parentName: null,
    name: "新闻管理",
    url: "config/news-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 365,
    parentId: 0,
    parentName: null,
    name: "理财矿机",
    url: "",
    perms: "",
    type: 0,
    icon: "form",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 383,
    parentId: 367,
    parentName: null,
    name: "C2C订单",
    url: "c2c/c2c_pay_order",
    perms: "",
    type: 1,
    icon: "config",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 390,
    parentId: 385,
    parentName: null,
    name: "申购活动",
    url: "subscribe/subscribe-action",
    perms: "",
    type: 1,
    icon: "shezhi",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 478,
    parentId: 473,
    parentName: null,
    name: "合约",
    url: "",
    perms: "",
    type: 0,
    icon: "down",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 492,
    parentId: 1,
    parentName: null,
    name: "银行卡订单",
    url: "c2c/bank_pay_order",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 505,
    parentId: 496,
    parentName: null,
    name: "合约",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 5,
    list: null,
    appType: "1",
  },
  {
    menuId: 519,
    parentId: 497,
    parentName: null,
    name: "永续合约(ETF)",
    url: "etf-spots/etf-transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 532,
    parentId: 498,
    parentName: null,
    name: "行情",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 350,
    parentId: 342,
    parentName: null,
    name: "横幅管理",
    url: "config/ad-config",
    perms: "",
    type: 1,
    icon: "config",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 356,
    parentId: 352,
    parentName: null,
    name: "角色管理",
    url: "sys/role",
    perms: "",
    type: 1,
    icon: "prod",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 367,
    parentId: 0,
    parentName: null,
    name: "C2C",
    url: "",
    perms: "",
    type: 0,
    icon: "form",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 384,
    parentId: 367,
    parentName: null,
    name: "C2C申诉",
    url: "c2c/c2c-pay-appeal",
    perms: "",
    type: 1,
    icon: "tubiao",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 481,
    parentId: 473,
    parentName: null,
    name: "永续持仓单(美股)",
    url: "us-spots/us-transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 506,
    parentId: 496,
    parentName: null,
    name: "永续持仓单(DC)",
    url: "cryptos-spots/cryptos-spots-transport",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 6,
    list: null,
    appType: "1",
  },
  {
    menuId: 520,
    parentId: 497,
    parentName: null,
    name: "永续委托单(ETF)",
    url: "etf-spots/etf-hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 533,
    parentId: 498,
    parentName: null,
    name: "行情管理(外汇)",
    url: "shop/shop-markets-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 542,
    parentId: 342,
    parentName: null,
    name: "管理",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 564,
    parentId: 352,
    parentName: null,
    name: "客服管理",
    url: "sys-config/customer-service-sys-config",
    perms: "",
    type: 1,
    icon: "admin",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 337,
    parentId: 0,
    parentName: null,
    name: "报表",
    url: "",
    perms: "",
    type: 0,
    icon: "menu",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 482,
    parentId: 473,
    parentName: null,
    name: "永续委托单(美股)",
    url: "us-spots/us-hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 507,
    parentId: 496,
    parentName: null,
    name: "永续委托单(DC)",
    url: "cryptos-spots/cryptos-hotSearch",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 7,
    list: null,
    appType: "1",
  },
  {
    menuId: 521,
    parentId: 497,
    parentName: null,
    name: "交割合约单(ETF)",
    url: "etf-spots/etf-pickAddr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 8,
    list: null,
    appType: "1",
  },
  {
    menuId: 534,
    parentId: 498,
    parentName: null,
    name: "行情品种管理(外汇)",
    url: "shop/shop-variety",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 8,
    list: null,
    appType: "1",
  },
  {
    menuId: 543,
    parentId: 342,
    parentName: null,
    name: "机器人刷单管理",
    url: "robot/robot-buy",
    perms: "",
    type: 1,
    icon: "prod",
    orderNum: 8,
    list: null,
    appType: "1",
  },
  {
    menuId: 565,
    parentId: 352,
    parentName: null,
    name: "系统用户管理",
    url: "sys-config/system-user-sys-config",
    perms: "",
    type: 1,
    icon: "shezhi",
    orderNum: 8,
    list: null,
    appType: "1",
  },
  {
    menuId: 342,
    parentId: 0,
    parentName: null,
    name: "配置",
    url: "",
    perms: "",
    type: 0,
    icon: "shezhi",
    orderNum: 8,
    list: null,
    appType: "1",
  },
  {
    menuId: 508,
    parentId: 496,
    parentName: null,
    name: "交割合约单(DC)",
    url: "cryptos-spots/cryptos-pickAddr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 8,
    list: null,
    appType: "1",
  },
  {
    menuId: 522,
    parentId: 497,
    parentName: null,
    name: "交割场控设置(ETF)",
    url: "etf-spots/etf-indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 535,
    parentId: 498,
    parentName: null,
    name: "永续合约管理(外汇)",
    url: "shop/shop-sustainable",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 544,
    parentId: 342,
    parentName: null,
    name: "机器人订单管理",
    url: "robot/robot-order",
    perms: "",
    type: 1,
    icon: "prod",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 566,
    parentId: 352,
    parentName: null,
    name: "日志",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 352,
    parentId: 0,
    parentName: null,
    name: "系统",
    url: "",
    perms: "",
    type: 0,
    icon: "menu",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 483,
    parentId: 473,
    parentName: null,
    name: "交割合约单(美股)",
    url: "us-spots/us-pickAddr",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 509,
    parentId: 496,
    parentName: null,
    name: "交割场控设置(DC)",
    url: "cryptos-spots/cryptos-indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 9,
    list: null,
    appType: "1",
  },
  {
    menuId: 523,
    parentId: 497,
    parentName: null,
    name: "行情",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 10,
    list: null,
    appType: "1",
  },
  {
    menuId: 536,
    parentId: 498,
    parentName: null,
    name: "交割合约管理(外汇)",
    url: "shop/shop-delivery",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 10,
    list: null,
    appType: "1",
  },
  {
    menuId: 567,
    parentId: 352,
    parentName: null,
    name: "账变记录",
    url: "sys-config/account-change-record-sys-config",
    perms: "",
    type: 1,
    icon: "form",
    orderNum: 10,
    list: null,
    appType: "1",
  },
  {
    menuId: 484,
    parentId: 473,
    parentName: null,
    name: "交割场控设置(美股)",
    url: "us-spots/us-indexImg",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 10,
    list: null,
    appType: "1",
  },
  {
    menuId: 510,
    parentId: 496,
    parentName: null,
    name: "行情",
    url: "",
    perms: "",
    type: 0,
    icon: "",
    orderNum: 10,
    list: null,
    appType: "1",
  },
  {
    menuId: 524,
    parentId: 497,
    parentName: null,
    name: "行情管理(ETF)",
    url: "etf-spots/etf-markets-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 11,
    list: null,
    appType: "1",
  },
  {
    menuId: 568,
    parentId: 352,
    parentName: null,
    name: "操作日志",
    url: "sys-config/operation-log-sys-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 11,
    list: null,
    appType: "1",
  },
  {
    menuId: 479,
    parentId: 473,
    parentName: null,
    name: "行情",
    url: "",
    perms: "",
    type: 0,
    icon: "down",
    orderNum: 11,
    list: null,
    appType: "1",
  },
  {
    menuId: 511,
    parentId: 496,
    parentName: null,
    name: "行情管理(DC)",
    url: "cryptos-spots/cryptos-markets-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 11,
    list: null,
    appType: "1",
  },
  {
    menuId: 512,
    parentId: 496,
    parentName: null,
    name: "行情品种管理(DC)",
    url: "cryptos-spots/cryptos-variety",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 12,
    list: null,
    appType: "1",
  },
  {
    menuId: 525,
    parentId: 497,
    parentName: null,
    name: "ETF币对管理",
    url: "etf-spots/etf-market-variety",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 12,
    list: null,
    appType: "1",
  },
  {
    menuId: 570,
    parentId: 352,
    parentName: null,
    name: "验证码日志",
    url: "sys-config/verification-code-log",
    perms: "",
    type: 1,
    icon: "log",
    orderNum: 12,
    list: null,
    appType: "1",
  },
  {
    menuId: 485,
    parentId: 473,
    parentName: null,
    name: "行情管理(美股)",
    url: "us-spots/us-markets-config",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 12,
    list: null,
    appType: "1",
  },
  {
    menuId: 513,
    parentId: 496,
    parentName: null,
    name: "永续合约管理(DC)",
    url: "cryptos-spots/cryptos-sustainable",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 13,
    list: null,
    appType: "1",
  },
  {
    menuId: 526,
    parentId: 497,
    parentName: null,
    name: "永续合约管理(ETF)",
    url: "etf-spots/etf-sustainable",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 13,
    list: null,
    appType: "1",
  },
  {
    menuId: 569,
    parentId: 352,
    parentName: null,
    name: "转账转换日志",
    url: "sys-config/dapp_change",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 13,
    list: null,
    appType: "1",
  },
  {
    menuId: 486,
    parentId: 473,
    parentName: null,
    name: "行情品种管理(美股)",
    url: "us-spots/us-variety",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 13,
    list: null,
    appType: "1",
  },
  {
    menuId: 514,
    parentId: 496,
    parentName: null,
    name: "交割合约管理(DC)",
    url: "cryptos-spots/cryptos-delivery",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 14,
    list: null,
    appType: "1",
  },
  {
    menuId: 527,
    parentId: 497,
    parentName: null,
    name: "交割合约管理(ETF)",
    url: "etf-spots/etf-delivery",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 14,
    list: null,
    appType: "1",
  },
  {
    menuId: 487,
    parentId: 473,
    parentName: null,
    name: "永续合约管理(美股)",
    url: "us-spots/us-sustainable",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 14,
    list: null,
    appType: "1",
  },
  {
    menuId: 488,
    parentId: 473,
    parentName: null,
    name: "交割合约管理(美股)",
    url: "us-spots/us-delivery",
    perms: "",
    type: 1,
    icon: "sql",
    orderNum: 15,
    list: null,
    appType: "1",
  },
  {
    menuId: 34,
    parentId: 0,
    parentName: null,
    name: "用户管理",
    url: "",
    perms: "",
    type: 0,
    icon: "admin",
    orderNum: 24,
    list: null,
    appType: "1",
  },
  {
    menuId: 399,
    parentId: 0,
    parentName: null,
    name: "用户关系管理",
    url: "",
    perms: "",
    type: 0,
    icon: "geren",
    orderNum: 25,
    list: null,
    appType: "1",
  },
  {
    menuId: 1,
    parentId: 0,
    parentName: null,
    name: "财务",
    url: "",
    perms: "",
    type: 0,
    icon: "system",
    orderNum: 26,
    list: null,
    appType: "1",
  },
  {
    menuId: 385,
    parentId: 0,
    parentName: null,
    name: "申购管理",
    url: "",
    perms: "",
    type: 0,
    icon: "mudedi",
    orderNum: 27,
    list: null,
    appType: "1",
  },
  {
    menuId: 396,
    parentId: 0,
    parentName: null,
    name: "机器人刷单管理",
    url: "",
    perms: "",
    type: 0,
    icon: "shezhi",
    orderNum: 28,
    list: null,
    appType: "1",
  },
  {
    menuId: 405,
    parentId: 0,
    parentName: null,
    name: "ETF(现货)",
    url: "",
    perms: "",
    type: 0,
    icon: "store",
    orderNum: 29,
    list: null,
    appType: "1",
  },
  {
    menuId: 406,
    parentId: 0,
    parentName: null,
    name: "ETF(合约)",
    url: "",
    perms: "",
    type: 0,
    icon: "sql",
    orderNum: 30,
    list: null,
    appType: "1",
  },
  {
    menuId: 429,
    parentId: 0,
    parentName: null,
    name: "ETF(行情)",
    url: "",
    perms: "",
    type: 0,
    icon: "bianji",
    orderNum: 31,
    list: null,
    appType: "1",
  },
  {
    menuId: 409,
    parentId: 0,
    parentName: null,
    name: "数字货币(现货)",
    url: "",
    perms: "",
    type: 0,
    icon: "store",
    orderNum: 32,
    list: null,
    appType: "1",
  },
  {
    menuId: 410,
    parentId: 0,
    parentName: null,
    name: "数字货币(合约)",
    url: "",
    perms: "",
    type: 0,
    icon: "sql",
    orderNum: 33,
    list: null,
    appType: "1",
  },
  {
    menuId: 411,
    parentId: 0,
    parentName: null,
    name: "数字货币(行情)",
    url: "",
    perms: "",
    type: 0,
    icon: "sql",
    orderNum: 34,
    list: null,
    appType: "1",
  },
  {
    menuId: 412,
    parentId: 0,
    parentName: null,
    name: "外汇交易(行情)",
    url: "",
    perms: "",
    type: 0,
    icon: "bianji",
    orderNum: 35,
    list: null,
    appType: "1",
  },
  {
    menuId: 63,
    parentId: 0,
    parentName: null,
    name: "外汇交易(合约)",
    url: "",
    perms: "",
    type: 0,
    icon: "log",
    orderNum: 36,
    list: null,
    appType: "1",
  },
  {
    menuId: 413,
    parentId: 0,
    parentName: null,
    name: "美股(现货)",
    url: "",
    perms: "",
    type: 0,
    icon: "store",
    orderNum: 37,
    list: null,
    appType: "1",
  },
  {
    menuId: 414,
    parentId: 0,
    parentName: null,
    name: "美股(合约)",
    url: "",
    perms: "",
    type: 0,
    icon: "sql",
    orderNum: 38,
    list: null,
    appType: "1",
  },
  {
    menuId: 415,
    parentId: 0,
    parentName: null,
    name: "美股(行情)",
    url: "",
    perms: "",
    type: 0,
    icon: "bianji",
    orderNum: 39,
    list: null,
    appType: "1",
  },
  {
    menuId: 436,
    parentId: 0,
    parentName: null,
    name: "币币",
    url: "",
    perms: "",
    type: 0,
    icon: "log",
    orderNum: 40,
    list: null,
    appType: "1",
  },
];
