export const tableOption = {
  border: true,
  stripe: true,
  align: "center",
  menuAlign: "center",
  menuFixed: false,
  menuWidth: 180,
  searchMenuSpan: 6,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  viewBtn: false,
  searchBtn: true,
  columnBtn: false,
  refreshBtn: true,
  props: {
    label: "label",
    value: "value",
  },
  column: [
    {
      label: "ID",
      prop: "id",
      width: 80,
      search: true,
      searchSpan: 6,
    },
    {
      label: "Phone",
      prop: "phone",
      minWidth: 160,
      search: true,
    },
    {
      label: "Phone All",
      prop: "phoneAll",
      minWidth: 180,
    },
    {
      label: "Email",
      prop: "email",
      minWidth: 220,
      search: true,
    },
  ],
};
