export const tableOption = {
  searchMenuSpan: 6,
  columnBtn: false,
  border: true,
  selection: false,
  index: false,
  indexLabel: '序号',
  stripe: true,
  menuAlign: 'center',
  menuWidth: 130,
  align: 'center',
  refreshBtn: true,
  searchSize: 'mini',
  addBtn: false,
  editBtn: false,
  delBtn: false,
  viewBtn: false,
  menu:false,
  props: {
    label: 'label',
    value: 'value'
  },
  column: [{
    label: '订单ID',
    prop: 'orderNo'
  }, {
    label: '买订单号',
    prop: 'orderNo'
  }, {
    label: '卖订单号',
    prop: 'orderNo'
  }, {
    label: '买家用户名/ID',
    prop: 'name'
  }, {
    label: '卖家用户名/ID',
    prop: 'MinimumTradingVolume'
  }, {
    label: '成交价格',
    prop: 'price'
  }, {
    label: '币对',
    prop: 'symbol'
  }, {
    label: '交易量',
    prop: 'symbolValue'
  }, {
    label: '交易额',
    prop: 'volume'
  }, {
    label: '买单手续费',
    prop: 'fee'
  }, {
    label: '卖单手续费',
    prop: 'fee'
  }, {
    label: '创建时间',
    prop: 'createTime'
  }]
}
