export const SET_COIN_LIST = 'SET_COIN_LIST'
export const GET_USERINFO = 'GET_USERINFO'
export const SET_LANGUAGE = 'SET_LANGUAGE'

export const SET_STAGE = 'SET_STAGE'
export const GET_USERLIST = 'GET_USERLIST'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_CURRENCY = 'SET_CURRENCY'
export const SET_HISTORY_LIST = 'SET_HISTORY_LIST'
export const OPCIONA_LIST = 'OPCIONA_LIST'
export const CITAS_LIST = 'CITAS_LIST'
export const IS_LOAD = 'IS_LOAD'
export const SET_THEME = 'SET_THEME'
export const SET_KEFU = 'SET_KEFU'
