server:
  port: 8111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auyeung?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: auyeung
    password: TC7JhaB3SGdxp5Jk
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: SELECT 1
  redis:
    redisson:
      config: classpath:redisson/redisson-prod.yml
      config-spider: classpath:redisson/redisson-spider.yml
    host: localhost
    port: 6379
    password: BHvK&mg6cckt
  freemarker:
    check-template-location: false
logging:
  config: classpath:logback/logback-prod.xml

jetcache:
  # 统计间隔，0表示不统计，开启后定期在控制台输出缓存信息
  statIntervalMinutes: 10
  # 是否把cacheName作为远程缓存key前缀
  areaInCacheName: true
  # @Cached和@CreateCache自动生成name的时候，为了不让name太长，hiddenPackages指定的包名前缀被截掉
  hiddenPackages: com.yami.trading
  # 本地缓存配置
  local:
    # default表示全部生效，也可以指定某个cacheName，可以配置更多的area(缓存分类，相当于命名空间)
    # 对应@Cached和@CreateCache的area属性。注意如果注解上没有指定area，默认值是"default"
    default:
      # 已支持可选：linkedhashmap、caffeine
      type: linkedhashmap
      # key转换器
      keyConvertor: fastjson
      # 以毫秒为单位，指定更新后多长时间就让缓存失效，当前只有本地缓存支持。0表示不使用这个功能
      expireAfterWriteInMillis: 100000
  # 远程缓存配置
  remote:
    default:
      # 缓存类型。tair、redis为当前支持的远程缓存
      type: redis
      # 其他可选：fastjson2 / jackson / fastjson
      keyConvertor: fastjson
      # jetcahe2.7的两级缓存支持更新以后失效其他JVM中的local cache
      broadcastChannel: jetcacheTrading
      # 采用Java序列化存储,其他可选：kryo/kryo5
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}
      database: 1

db:
  ip: localhost
  port: 3306
  database.name: auyeung-root
  username: root
  password: dfgFGHR45623$&
  backup.path: /backup
  
http.server.host: http://localhost:8080/images/
admin_rest_url: https://enjdhdg.site/api
images.dir: /mydata/img/
admin_url: https://localhost:8080/admin
web_url: http://localhost:8080/wap/

email:
  host: smtp.gmail.com
  username: test
  password: test
  from: smtp.gmail.com

exchange:
  rate: https://openexchangerates.org/api/latest.json?app_id=1de9ea307c074f2198d1052117464aba

#config:
#  timezone:
#    # 配置当前盘口存储数据使用的时区
#    record: GMT-5
#    # 配置当前盘口展示数据使用的时区
#    show: GMT-5

sign:
  encryption-key: d78585e683ed11eaa13f0242ac110003
  version-number: