spring:
  # 环境 dev|test|prod
  profiles:
    active: prod
  #文件上传设置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/New_York
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#    view:
#      prefix: classpath:/static/
#      suffix: .html
#  thymeleaf:
#    prefix: classpath:/static/
#    suffix: .html
#    encoding: UTF-8
#    cache: false

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations:
    - classpath*:/mapper/**/*Mapper.xml
    - classpath*:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定�?2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表�?      id-type: AUTO
      #字段策略 0:"忽略判断",1:"�?NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命�?      table-underline: true
oss:
  aws:
    s3:
      bucketName: trading-order-test

sign:
  encryption-key: d78585e683ed11eaa13f0242ac110003
  version-number:
